-- ═══════════════════════════════════════════════════════════════
--  Extension du catalogue — fruits, légumes et autres produits
--  courants des grandes surfaces françaises, non couverts par le
--  catalogue de départ (seed.sql).
--  À lancer APRÈS schema.sql et seed.sql — Supabase → SQL Editor → Run
-- ═══════════════════════════════════════════════════════════════

insert into produits (cle, nom, categorie, unite, prix_ref, mois_saison, illustration) values
  -- Légumes
  ('aubergine',   'Aubergine',        'Légumes', 'kg',        3.20, '{6,7,8,9,10}',            null),
  ('brocoli',     'Brocoli',          'Légumes', 'pièce',     2.10, '{6,7,8,9,10,11}',         null),
  ('choufleur',   'Chou-fleur',       'Légumes', 'pièce',     2.60, '{9,10,11,12,1,2}',        null),
  ('chou',        'Chou',             'Légumes', 'pièce',     1.90, '{9,10,11,12,1,2,3}',      null),
  ('poireau',     'Poireau',          'Légumes', 'botte',     2.30, '{9,10,11,12,1,2,3}',      null),
  ('oignon',      'Oignon',           'Légumes', 'kg',        1.80, '{7,8,9,10,11,12,1,2,3,4,5,6}', null),
  ('echalote',    'Échalote',         'Légumes', 'kg',        4.90, '{6,7,8,9}',               null),
  ('ail',         'Ail',              'Légumes', 'kg',        7.90, '{7,8,9}',                 null),
  ('epinard',     'Épinard',          'Légumes', 'kg',        4.50, '{3,4,5,9,10,11}',         null),
  ('haricotvert', 'Haricot vert',     'Légumes', 'kg',        5.90, '{6,7,8,9}',               null),
  ('petitpois',   'Petit pois',       'Légumes', 'kg',        4.20, '{5,6,7}',                 null),
  ('radis',       'Radis',            'Légumes', 'botte',     1.50, '{4,5,6,7,8,9}',           null),
  ('betterave',   'Betterave',        'Légumes', 'kg',        2.40, '{6,7,8,9,10,11}',         null),
  ('panais',      'Panais',           'Légumes', 'kg',        2.90, '{10,11,12,1,2,3}',        null),
  ('navet',       'Navet',            'Légumes', 'kg',        2.10, '{9,10,11,12,1,2,3}',      null),
  ('rutabaga',    'Rutabaga',         'Légumes', 'kg',        2.30, '{10,11,12,1,2,3}',        null),
  ('artichaut',   'Artichaut',        'Légumes', 'pièce',     1.90, '{5,6,7}',                 null),
  ('asperge',     'Asperge',          'Légumes', 'botte',     6.90, '{4,5,6}',                 null),
  ('champignon',  'Champignon',       'Légumes', 'kg',        5.40, '{9,10,11}',               null),
  ('endive',      'Endive',           'Légumes', 'kg',        2.80, '{10,11,12,1,2,3}',        null),
  ('fenouil',     'Fenouil',          'Légumes', 'pièce',     2.20, '{6,7,8,9,10}',            null),
  ('celeri',      'Céleri',           'Légumes', 'pièce',     1.70, '{9,10,11,12}',            null),
  ('concombre',   'Concombre',        'Légumes', 'pièce',     1.40, '{5,6,7,8,9}',             null),
  ('mais',        'Maïs doux',        'Légumes', 'pièce',     0.90, '{7,8,9}',                 null),
  ('blette',      'Blette',           'Légumes', 'botte',     2.60, '{6,7,8,9,10}',            null),

  -- Fruits
  ('abricot',     'Abricot',          'Fruits', 'kg',         4.90, '{6,7,8}',                 null),
  ('peche',       'Pêche',            'Fruits', 'kg',         3.90, '{6,7,8,9}',               null),
  ('prune',       'Prune',            'Fruits', 'kg',         3.40, '{7,8,9}',                 null),
  ('cerise',      'Cerise',           'Fruits', 'kg',         8.90, '{5,6,7}',                 null),
  ('raisin',      'Raisin',           'Fruits', 'kg',         4.20, '{8,9,10}',                null),
  ('melon',       'Melon',            'Fruits', 'pièce',      2.90, '{6,7,8,9}',               null),
  ('pasteque',    'Pastèque',         'Fruits', 'pièce',      5.90, '{6,7,8}',                 null),
  ('poire',       'Poire',            'Fruits', 'kg',         3.10, '{9,10,11,12,1}',          null),
  ('kiwi',        'Kiwi',             'Fruits', 'kg',         4.50, '{11,12,1,2,3}',           null),
  ('framboise',   'Framboise',        'Fruits', 'barquette',  4.90, '{6,7,8,9}',               null),
  ('myrtille',    'Myrtille',         'Fruits', 'barquette',  5.20, '{7,8}',                   null),
  ('cassis',      'Cassis',           'Fruits', 'barquette',  4.60, '{7,8}',                   null),
  ('groseille',   'Groseille',        'Fruits', 'barquette',  4.40, '{6,7}',                   null),
  ('mirabelle',   'Mirabelle',        'Fruits', 'kg',         4.10, '{8,9}',                   null),
  ('clementine',  'Clémentine',       'Fruits', 'kg',         3.20, '{11,12,1,2}',             null),
  ('citron',      'Citron',           'Fruits', 'kg',         3.50, '{1,2,3,4,5,6,7,8,9,10,11,12}', null),
  ('orange',      'Orange',           'Fruits', 'kg',         2.70, '{11,12,1,2,3,4}',         null),
  ('pamplemousse','Pamplemousse',     'Fruits', 'pièce',      1.60, '{11,12,1,2,3}',           null),
  ('figue',       'Figue',            'Fruits', 'barquette',  4.80, '{8,9,10}',                null),
  ('coing',       'Coing',            'Fruits', 'kg',         3.00, '{9,10,11}',               null),
  ('rhubarbe',    'Rhubarbe',         'Fruits', 'kg',         3.40, '{4,5,6}',                 null),
  ('noix',        'Noix',             'Fruits', 'kg',         7.90, '{9,10,11}',               null),
  ('noisette',    'Noisette',         'Fruits', 'kg',         8.90, '{9,10}',                  null),
  ('chataigne',   'Châtaigne',        'Fruits', 'kg',         6.50, '{10,11,12}',              null),

  -- Œufs & laitages
  ('lait',        'Lait',             'Œufs & laitages', 'litre',   1.10, '{1,2,3,4,5,6,7,8,9,10,11,12}', null),
  ('beurre',      'Beurre fermier',   'Œufs & laitages', 'pièce',   2.90, '{1,2,3,4,5,6,7,8,9,10,11,12}', null),
  ('yaourt',      'Yaourt fermier',   'Œufs & laitages', 'pot',     0.70, '{1,2,3,4,5,6,7,8,9,10,11,12}', null),
  ('creme',       'Crème fraîche',    'Œufs & laitages', 'pot',     2.20, '{1,2,3,4,5,6,7,8,9,10,11,12}', null)
on conflict (cle) do nothing;

insert into varietes (produit_id, nom, description, illustration)
select p.id, v.nom, v.descr, v.ill from produits p join (values
  ('aubergine','Violette longue','Classique, chair fondante',null),
  ('aubergine','Ronde de Valence','Charnue, peu de graines',null),
  ('brocoli','Calabrese','Gros bouquet vert foncé',null),
  ('choufleur','Blanc classique','Ferme et compact',null),
  ('chou','Chou vert','Croquant, pour la soupe',null),
  ('chou','Chou rouge','Coloré, parfait cru en salade',null),
  ('poireau','Poireau d''hiver','Résistant au froid',null),
  ('oignon','Oignon jaune','De garde, saveur classique',null),
  ('oignon','Oignon rouge','Doux, idéal cru',null),
  ('echalote','Échalote grise','Parfumée, longue conservation',null),
  ('ail','Ail blanc','Classique, séché',null),
  ('ail','Ail rose de Lautrec','Parfumé, IGP',null),
  ('epinard','Épinard frais','Feuilles tendres',null),
  ('haricotvert','Haricot fin','Croquant, sans fil',null),
  ('petitpois','Petit pois frais','Sucré, à écosser',null),
  ('radis','Radis rose','Croquant, légèrement piquant',null),
  ('betterave','Betterave rouge','Cuite ou crue, sucrée',null),
  ('betterave','Betterave chioggia','Rayée, douce',null),
  ('panais','Panais classique','Doux, goût de noisette',null),
  ('navet','Navet blanc','Fondant, cuisiné en pot-au-feu',null),
  ('rutabaga','Rutabaga classique','Goût prononcé, d''hiver',null),
  ('artichaut','Camus de Bretagne','Gros cœur charnu',null),
  ('asperge','Asperge verte','Croquante, goût prononcé',null),
  ('asperge','Asperge blanche','Douce, cultivée sous terre',null),
  ('champignon','Champignon de Paris','Blanc, classique',null),
  ('champignon','Pleurote','Parfumé, texture ferme',null),
  ('endive','Endive de pleine terre','Légèrement amère',null),
  ('fenouil','Fenouil classique','Croquant, goût anisé',null),
  ('celeri','Céleri rave','Pour purée ou rémoulade',null),
  ('celeri','Céleri branche','Croquant, en soupe ou apéritif',null),
  ('concombre','Concombre classique','Frais et croquant',null),
  ('mais','Maïs doux frais','Sucré, à griller ou bouillir',null),
  ('blette','Blette à côtes','Feuilles et côtes fondantes',null),
  ('abricot','Bergeron','Sucré et parfumé',null),
  ('peche','Pêche jaune','Juteuse et sucrée',null),
  ('peche','Pêche blanche','Douce, peu acidulée',null),
  ('peche','Nectarine','Peau lisse, chair ferme',null),
  ('prune','Reine-Claude','Verte, très sucrée',null),
  ('prune','Quetsche','Violette, idéale en tarte',null),
  ('cerise','Bigarreau','Ferme et sucrée',null),
  ('cerise','Griotte','Acidulée, pour confiture',null),
  ('raisin','Chasselas','Blond, sucré',null),
  ('raisin','Muscat','Très parfumé',null),
  ('melon','Charentais','Chair orange, très parfumé',null),
  ('pasteque','Pastèque classique','Chair rouge, très juteuse',null),
  ('poire','Williams','Fondante et juteuse',null),
  ('poire','Comice','Sucrée, texture beurrée',null),
  ('kiwi','Kiwi vert','Acidulé, classique',null),
  ('framboise','Framboise d''été','Parfumée, fragile',null),
  ('myrtille','Myrtille sauvage','Petite, très parfumée',null),
  ('cassis','Cassis noir','Acidulé, pour sirop et confiture',null),
  ('groseille','Groseille rouge','Acidulée, en grappe',null),
  ('mirabelle','Mirabelle de Lorraine','Petite, très sucrée',null),
  ('clementine','Clémentine de Corse','Sans pépin, sucrée',null),
  ('citron','Citron jaune','Classique, très acide',null),
  ('citron','Citron vert','Parfumé, pour cocktails et cuisine',null),
  ('orange','Orange à jus','Juteuse et sucrée',null),
  ('orange','Orange sanguine','Chair rouge, parfumée',null),
  ('pamplemousse','Pamplemousse rose','Doux, peu amer',null),
  ('figue','Figue noire','Sucrée, chair rouge',null),
  ('figue','Figue blanche','Douce, peau claire',null),
  ('coing','Coing classique','Pour gelée et pâte de coing',null),
  ('rhubarbe','Rhubarbe rouge','Acidulée, pour tarte et compote',null),
  ('noix','Noix fraîche','À écaler, goût doux',null),
  ('noisette','Noisette fraîche','Croquante, à décortiquer',null),
  ('chataigne','Châtaigne classique','À griller ou en purée',null),
  ('lait','Lait cru','Entier, non pasteurisé',null),
  ('lait','Lait pasteurisé','Entier ou demi-écrémé',null),
  ('beurre','Beurre doux','Baratté à la ferme',null),
  ('beurre','Beurre demi-sel','Légèrement salé',null),
  ('yaourt','Yaourt nature','Onctueux, lait entier',null),
  ('yaourt','Yaourt aux fruits','Parfumé aux fruits du jardin',null),
  ('creme','Crème fraîche épaisse','Riche, pour cuisiner',null),
  ('creme','Crème liquide','Légère, pour sauces',null)
) as v(cle, nom, descr, ill) on v.cle = p.cle
where not exists (select 1 from varietes x where x.produit_id = p.id and x.nom = v.nom);
